{% set name = "quast" %}
{% set version = "4.6.1" %}
{% set hash = "29118bff957af6d1b36136735450ddc8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0 
  string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}

source:
  fn: {{ name|lower }}-{{ version }}.tar.gz
  url: http://downloads.sourceforge.net/project/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  md5: {{ hash }}
  patches:
    - gnuplot_fix.patch
    - print_debug.patch

requirements:
  build:
    - gcc
    - boost {{CONDA_BOOST}}*
    - perl
    - python
    - matplotlib
    - openjdk
    - joblib
    - simplejson
    - gnuplot

  run:
    - boost {{CONDA_BOOST}}*
    - perl
    - python
    - libgcc
    - matplotlib
    - openjdk
    - joblib
    - simplejson
    - gnuplot

test:
  source_files:
    - test_data
  commands:
    - quast --version
    - evil-exit-monkeypatch.py <$(which quast) --test --force-nucmer
    - metaquast --version
    - evil-exit-monkeypatch.py <$(which metaquast) --test --force-nucmer

about:
  home: https://sourceforge.net/projects/{{ name|lower }}/
  license: GPL2
  license_file: LICENSE.txt
  summary: Quality Assessment Tool for Genome Assemblies
